version: '3.2'

services:
  pb:
    build: .
    depends_on:
      - mongo
    ports:
      - '10002:10002'
    volumes:
      - ./config.yaml.example:/etc/xdg/pb/config.yaml
    # environment:
    #  - 'LISTEN_ADDRESS=0.0.0.0'
    #  - 'LISTEN_PORT=10002'
    #  - 'CDN_PREFIX=//d34zelngniy2d8.cloudfront.net'

  mongo:
    image: mongo
